services:
  app:
    image: tonycava/meal-prep:latest
    container_name: meal-prep-app
    volumes:
      - web-services:./prisma/dev.db
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8090:8090"
    env_file: .env

volumes:
  web-services: